### ISSUE TITLE
RobinhoodShell 

### ISSUE THREAD

**Issue by kayodeadaniel** [anilshanbhag/RobinhoodShell#32]
I get this when I try to execute ./shell.py

:~/RobinhoodShell$ ./shell.py
  File "./shell.py", line 123
    change = f"{change:.3f}"
                                         ^
SyntaxError: invalid syntax

please kindly look at this please
am using python  3

**Comment by FCCMac** [comment]
This is a python version issue, as f strings are a 3.6 feature. The easy solution is to upgrade your python install. If another module requires an earlier version of python, then you'll have to swap out all of the f strings with `string.format()` calls instead. I'm actually working on this right now since zipline requires 3.5.

**Comment by FCCMac** [comment]
I opened a PR to fix this [here](https://github.com/anilshanbhag/RobinhoodShell/pull/34).

**Comment by anilshanbhag** [comment]
Fixed by #35

**Comment by anilshanbhag** [comment]
fixed by #34
